name: mlr_colabfold_202408
channels:
  - nvidia
  - sdvillal
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - absl-py=2.1.0
  - anyio=4.4.0
  - aom=3.9.1
  - appdirs=1.4.4
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - aria2=1.37.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - astunparse=1.6.3
  - async-lru=2.0.4
  - attrs=24.1.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - biopython=1.84
  - bleach=6.1.0
  - blosc=1.21.6
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.32.3
  - ca-certificates=2024.7.4
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - chex=0.1.86
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.2.1
  - cuda-nvcc=12.4.131
  - cuda-version=11.8
  - cudatoolkit=11.8.0
  - cudnn=8.9.7.29
  - cycler=0.12.1
  - dataclasses=0.8
  - dav1d=1.2.1
  - debugpy=1.8.3
  - decorator=5.1.1
  - defusedxml=0.7.1
  - dm-haiku=0.0.12
  - dm-tree=0.1.8
  - entrypoints=0.4
  - etils=1.9.2
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - flatbuffers=24.3.25
  - flax=0.8.5
  - fonttools=4.53.1
  - fqdn=1.5.1
  - freetype=2.12.1
  - gast=0.5.5
  - gawk=5.3.0
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - giflib=5.2.2
  - gmp=6.3.0
  - google-pasta=0.2.0
  - grpcio=1.62.2
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.11.0
  - hdf5=1.14.3
  - hhsuite=3.3.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=75.1
  - idna=3.7
  - immutabledict=4.2.0
  - importlib-metadata=8.2.0
  - importlib_metadata=8.2.0
  - importlib_resources=6.4.0
  - iniconfig=2.0.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - ipywidgets=8.1.3
  - isoduration=20.11.0
  - jax=0.4.23
  - jaxlib=0.4.23
  - jedi=0.19.1
  - jinja2=3.1.4
  - jmp=0.0.4
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.0.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.2
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.11
  - kalign2=2.04
  - keras=3.4.1
  - keyutils=1.6.1
  - kiwisolver=1.4.5
  - krb5=1.21.3
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libavif16=1.1.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.9.1
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - libgrpc=1.62.2
  - libiconv=1.17
  - libidn2=2.3.7
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=14.1.0
  - libtiff=4.6.0
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mistune=3.0.2
  - ml_dtypes=0.4.0
  - mmseqs2=15.6f452
  - mpfr=4.2.1
  - msgpack-python=1.0.8
  - munkres=1.0.7
  - namex=0.0.8
  - nbclient=0.10.0
  - nbconvert=7.16.4
  - nbconvert-core=7.16.4
  - nbconvert-pandoc=7.16.4
  - nbformat=5.10.4
  - nccl=2.22.3.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - notebook=7.2.1
  - notebook-shim=0.2.4
  - numpy=1.26.4
  - ocl-icd=2.3.2
  - ocl-icd-system=1.0.0
  - openjpeg=2.5.2
  - openmm=8.0.0
  - openssl=3.3.1
  - opt-einsum=3.3.0
  - opt_einsum=3.3.0
  - optax=0.2.2
  - optree=0.12.1
  - orbax-checkpoint=0.4.4
  - overrides=7.7.0
  - packaging=24.1
  - pandas=2.2.2
  - pandoc=3.3
  - pandocfilters=1.5.0
  - parallel=20160622
  - parso=0.8.4
  - pdbfixer=1.9
  - perl=5.32.1
  - perl-threaded=5.32.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - pluggy=1.5.0
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - protobuf=4.25.3
  - psutil=6.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11-abi=4
  - pycparser=2.22
  - pygments=2.18.0
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - pytest=8.3.2
  - python=3.11.9
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-flatbuffers=24.3.25
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.11
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - qhull=2020.2
  - qtconsole-base=5.5.2
  - qtpy=2.4.1
  - rav1e=0.6.6
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - rpds-py=0.19.1
  - scipy=1.14.0
  - send2trash=1.8.3
  - setuptools=72.1.0
  - six=1.16.0
  - snappy=1.2.1
  - sniffio=1.3.1
  - soupsieve=2.5
  - stack_data=0.6.2
  - svt-av1=2.1.2
  - tabulate=0.9.0
  - tensorboard=2.17.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.17.0
  - tensorflow-base=2.17.0
  - tensorflow-estimator=2.17.0
  - tensorstore=0.1.62
  - termcolor=2.4.0
  - terminado=0.18.1
  - tinycss2=1.3.0
  - tk=8.6.13
  - tomli=2.0.1
  - toolz=0.12.1
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzdata=2024a
  - uri-template=1.3.0
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - webcolors=24.6.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.0.3
  - wget=1.21.4
  - wheel=0.44.0
  - widgetsnbextension=4.0.11
  - wrapt=1.16.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - alphafold-colabfold==2.3.6
      - alv==1.8.0
      - colabfold==1.5.5
      - contextlib2==21.6.0
      - ml-collections==0.1.1
